# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
specification/protocol/open_inference_rest.yaml:
  no-empty-servers:
    - '#/servers'
  operation-4xx-response:
    - '#/paths/~1v2~1health~1live/get/responses'
    - '#/paths/~1v2~1health~1ready/get/responses'
  security-defined:
    - '#/paths/~1v2/get'
    - '#/paths/~1v2~1health~1live/get'
    - '#/paths/~1v2~1health~1ready/get'
    - '#/paths/~1v2~1models~1{MODEL_NAME}~1ready/get'
    - '#/paths/~1v2~1models~1{MODEL_NAME}~1versions~1{MODEL_VERSION}~1ready/get'
    - '#/paths/~1v2~1models~1{MODEL_NAME}/get'
    - '#/paths/~1v2~1models~1{MODEL_NAME}~1versions~1{MODEL_VERSION}/get'
    - '#/paths/~1v2~1models~1{MODEL_NAME}~1infer/post'
    - '#/paths/~1v2~1models~1{MODEL_NAME}~1versions~1{MODEL_VERSION}~1infer/post'
